#!/bin/bash

# BSCScan Contract Verification Script
# Contract: 0x3E1Cf18D6b94A4aCC438176b87E1387280aC87d4
# Chain: BNB Testnet (Chain ID 97)

CONTRACT_ADDRESS="0x3E1Cf18D6b94A4aCC438176b87E1387280aC87d4"
COMPILER_VERSION="v0.8.24+commit.e11b9ed9"
API_KEY="VVJZYE57SQPKNV6BWHBSXQK6N64MBRG33K"
CHAIN_ID="97"

echo "=========================================="
echo "Smart Contract Verification - BSCScan"
echo "=========================================="
echo ""
echo "Contract: $CONTRACT_ADDRESS"
echo "Chain: BNB Testnet (Chain ID: $CHAIN_ID)"
echo "Compiler: Solidity 0.8.24"
echo ""

# Method 1: Using BSCScan API (Recommended)
echo "Method 1: BSCScan API Verification"
echo "-----------------------------------"
echo ""
echo "Run this command to verify via API:"
echo ""
echo "curl -X POST 'https://api-testnet.bscscan.com/api' \\"
echo "  --data-urlencode 'module=contract' \\"
echo "  --data-urlencode 'action=verifysourcecode' \\"
echo "  --data-urlencode 'contractaddress=$CONTRACT_ADDRESS' \\"
echo "  --data-urlencode 'sourceCode=@flattened.sol' \\"
echo "  --data-urlencode 'codeformat=solidity-single-file' \\"
echo "  --data-urlencode 'contractname=GachardCard' \\"
echo "  --data-urlencode 'compilerversion=$COMPILER_VERSION' \\"
echo "  --data-urlencode 'optimizationUsed=1' \\"
echo "  --data-urlencode 'runs=200' \\"
echo "  --data-urlencode 'licenseType=3' \\"
echo "  --data-urlencode 'apikey=$API_KEY'"
echo ""

# Method 2: Manual Verification on BSCScan Website
echo "Method 2: Manual Verification (Recommended for beginners)"
echo "----------------------------------------------------------"
echo ""
echo "1. Go to: https://testnet.bscscan.com/address/$CONTRACT_ADDRESS#code"
echo "2. Click 'Verify and Publish' button"
echo "3. Select: 'Solidity (Single file)'"
echo "4. Compiler: v0.8.24+commit.e11b9ed9"
echo "5. License: MIT License"
echo "6. Paste content of 'flattened.sol' into 'Contract Code' field"
echo "7. Optimization: Yes, 200 runs"
echo "8. Click 'Verify and Publish'"
echo ""

# Method 3: Using Foundry (if installed)
echo "Method 3: Foundry Verification (Advanced)"
echo "-------------------------------------------"
echo ""
echo "cd contracts"
echo "forge verify-contract \\"
echo "  --chain-id $CHAIN_ID \\"
echo "  --compiler-version 0.8.24 \\"
echo "  --optimizer-runs 200 \\"
echo "  $CONTRACT_ADDRESS \\"
echo "  src/GachardCard.sol:GachardCard \\"
echo "  --etherscan-api-key $API_KEY"
echo ""

echo "=========================================="
echo "What You Get After Verification:"
echo "=========================================="
echo ""
echo "✅ Contract Source Code - Readable Solidity code on BSCScan"
echo "✅ Contract ABI - JSON ABI for interaction"
echo "✅ Contract Creation Code - Bytecode used to deploy"
echo "✅ Deployed ByteCode - Bytecode on blockchain"
echo ""

echo "=========================================="
echo "For Hackathon Submission:"
echo "=========================================="
echo ""
echo "MOST IMPORTANT (Required):"
echo "  ✅ Contract Source Code - Shows transparency"
echo "  ✅ Contract ABI - Needed for interaction"
echo ""
echo "NICE TO HAVE (Optional):"
echo "  ○ Contract Creation Code - For completeness"
echo "  ○ Deployed ByteCode - For completeness"
echo ""

echo "=========================================="
echo "After Verification - Update README:"
echo "=========================================="
echo ""
echo "Add this to README.md:"
echo ""
echo "## Smart Contract Verification"
echo "Contract verified on BSCScan:"
echo "- Source Code: https://testnet.bscscan.com/address/$CONTRACT_ADDRESS#code"
echo "- ABI: Available on BSCScan contract page"
echo "- Compiler: Solidity 0.8.24"
echo "- Optimization: Enabled (200 runs)"
